- name: Docker prerequisites are present
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
    state: latest
    force: yes
  tags: [docker]

#- name: Add Docker’s official GPG key
#  ansible.builtin.shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add an Apt signing key to a specific keyring file
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

#- name: Add Docker repository and update apt cache
# apt_repository:
#    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs)  stable"
#    update_cache: yes
#    state: present
#  tags: [docker]

- name: Set up Docker stable repository
  ansible.builtin.shell: >
    echo 
    "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
    https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  
- name: Update apt cache   
  apt:
    update_cache: yes

- name: Docker is present
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: latest
    force: yes
  tags: [docker]

- name: Python-pip is present
  apt: name=python-pip state=present
  tags: [docker]

- name: Docker-py is present
  pip: name=docker-py version=1.6.0 state=present
  tags: [docker]

- name: Docker Compose is present
  get_url:
    url: https://github.com/docker/compose/releases/download/1.11.1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    timeout: 60
  tags: [docker]

- name: Docker Compose permissions are set
  file:
    path: /usr/local/bin/docker-compose
    mode: 0755
  tags: [docker]
